- packages/core/src/generators/utils/generate-project.ts
> Add Nx scopes to C# namespace

- .all-contributorsrc
- README.md
- packages/core/src/generators/nuget-reference/schema.json
The `version` option for the `nuget-reference` generator has a copy-pasted description from a directory option.
> docs(core): correct description of version option for nuget-reference

- packages/core/src/generators/init/generator.ts
> fix(core): #38 - Misc fixes for .gitignore updates

- packages/core/generators.json
- packages/core/src/generators/init/generator.spec.ts
- packages/core/src/generators/init/generator.ts
- packages/core/src/generators/restore/generator.spec.ts
- packages/core/src/generators/restore/generator.ts
- packages/core/src/generators/restore/schema.json
- packages/core/src/generators/utils/generate-project.spec.ts
- packages/core/src/generators/utils/generate-project.ts
- packages/dotnet/src/lib/core/dotnet.client.ts
Add the features and utilities for upcoming generators and executors that require .NET tools.
Fixes #44
> Add groundwork for tool management

- docs/core/index.md
- e2e/core-e2e/tests/nx-dotnet.spec.ts
- package.json
- packages/core/README.md
- packages/core/migrations.json
- packages/core/src/generators/utils/generate-project.ts
- packages/core/src/generators/utils/generate-test-project.ts
- packages/core/src/generators/utils/resolve-version-mismatch.ts
- packages/core/src/index.ts
- packages/core/src/migrations/1.2.0/add-module-boundaries-check/migrate.ts
- packages/core/src/tasks/check-module-boundaries.spec.ts
- packages/core/src/tasks/check-module-boundaries.ts
- packages/typescript/src/generators/typescript/generator.ts
- packages/utils/src/lib/models/index.ts
- packages/utils/src/lib/models/nx-dotnet-config.interface.ts
- packages/utils/src/lib/models/nx.ts
- packages/utils/src/lib/utility-functions/config.ts
- packages/utils/src/lib/utility-functions/glob.ts
- packages/utils/src/lib/utility-functions/workspace.ts
- tools/scripts/hooks/documentation.check.ts
- yarn.lock
nx-dotnet understands nx-enforce-module-boundaries from general nx eslint setup.
> feat(core): #81 support for nx-enforce-module-boundaries

- .github/workflows/pr.yml
- docs/core/executors/test.md
- packages/core/src/executors/build/executor.ts
- packages/core/src/executors/publish/executor.spec.ts
- packages/core/src/executors/publish/executor.ts
- packages/core/src/executors/publish/schema.d.ts
- packages/core/src/executors/serve/executor.ts
- packages/core/src/executors/test/executor.ts
- packages/core/src/executors/test/schema.d.ts
- packages/core/src/executors/test/schema.json
- packages/core/src/tasks/check-module-boundaries.ts
- packages/dotnet/package.json
- packages/dotnet/src/lib/core/dotnet.client.ts
- packages/utils/src/lib/utility-functions/childprocess.ts
- packages/utils/src/lib/utility-functions/index.ts
- packages/utils/src/lib/utility-functions/is-buffer.ts
- packages/utils/src/lib/utility-functions/workspace.ts
To accomplish this `dotnet` must be launched from the project's root directories.
Closes #87
Closes #86
> feat(core): pick up global.json overrides from project level

- e2e/core-e2e/tests/nx-dotnet.spec.ts
- packages/utils/src/lib/utility-functions/e2e/nx.ts
- packages/utils/src/lib/utility-functions/workspace.ts
- smoke/core/tests/nx-dotnet.spec.ts
> fix: use exact project paths

- docs/core/guides/handling-solutions.md
Looked for the same problem on other documentation files and could not find any other similar issues.
Fixes #311
> docs(core): fix JSON format on Handling Solution help page

- e2e/core-e2e/tests/nx-dotnet.spec.ts
- packages/core/src/graph/infer-project.ts
> fix(core): infer-projects should work with nx daemon

- packages/dotnet/.babelrc
- packages/dotnet/src/lib/core/dotnet.client.spec.ts
- packages/dotnet/src/lib/core/dotnet.client.ts
> fix(dotnet): update handling of extraParameters to be compatible with spawn

- package.json
- packages/utils/src/lib/utility-functions/glob.ts
- yarn.lock
> feat(utils): replace glob with fast-glob

- e2e/core-e2e/tests/nx-dotnet.spec.ts
- e2e/utils/index.ts
- packages/dotnet/src/lib/core/dotnet.client.ts
- tools/scripts/e2e.ts
> fix(dotnet): dotnet watch --project ... test should work

- docs/core/generators/application.md
- docs/core/generators/library.md
- docs/core/generators/test.md
- e2e/core-e2e/tests/nx-dotnet.spec.ts
- packages/core/src/generators/app/generator.spec.ts
- packages/core/src/generators/app/schema.json
- packages/core/src/generators/lib/generator.spec.ts
- packages/core/src/generators/lib/schema.json
- packages/core/src/generators/test/generator.spec.ts
- packages/core/src/generators/test/schema.json
- packages/core/src/generators/utils/generate-project.spec.ts
- packages/core/src/generators/utils/generate-project.ts
- packages/core/src/generators/utils/generate-test-project.spec.ts
- packages/core/src/generators/utils/generate-test-project.ts
- packages/core/src/models/project-generator-schema.ts
- packages/core/src/models/test-generator-schema.ts
Added pathScheme (default nx) to  app,lib,test generation.  Added and
e2e test and updated generated docs
This addresses issue #427
> feat(core): added pathScheme for project generators

- README.md
Updated README to include that nrwl/js plugin is required
See https://github.com/nx-dotnet/nx-dotnet/issues/490
> chore(repo): update readme to include @nrwl/js as a prerequisite

- packages/core/src/generators/swagger-typescript/__snapshots__/generator.spec.ts.snap
- packages/core/src/generators/swagger-typescript/generator.spec.ts
- packages/core/src/generators/swagger-typescript/generator.ts
- packages/core/src/generators/swagger-typescript/templates/interface/__interfaceFileName__.ts__tmpl__
> fix(core): remove duplicate imports generated by swagger-typescript

- docs/core/executors/build.md
- docs/core/executors/test.md
- packages/core/src/executors/build/executor.ts
- packages/core/src/executors/build/schema.d.ts
- packages/core/src/executors/build/schema.json
- packages/core/src/executors/test/executor.ts
- packages/core/src/executors/test/schema.d.ts
- packages/core/src/executors/test/schema.json
- packages/dotnet/src/lib/core/dotnet.client.ts
> fix(core): add extraParameters support to build and test executors

- packages/utils/src/lib/utility-functions/glob.spec.ts
- packages/utils/src/lib/utility-functions/glob.ts
> chore(core): add more logging when unable to find a project

- README.md
I know this is a nano-detail, but I like what you're doing.
> chore(repo): Fixed broken link in readme

- docs/core/generators/move.md
- docs/core/index.md
- docs/index.md
- packages/core/generators.json
- packages/core/src/generators/move/generator.spec.ts
- packages/core/src/generators/move/generator.ts
- packages/core/src/generators/move/schema.d.ts
- packages/core/src/generators/move/schema.json
- tsconfig.base.json
> feat(core): add move generator

- docs/core/generators/add-swagger-target.md
- docs/core/generators/application.md
- package.json
- packages/core/src/generators/add-swagger-target/add-swagger-target.ts
- packages/core/src/generators/add-swagger-target/schema.d.ts
- packages/core/src/generators/add-swagger-target/schema.json
- packages/core/src/generators/app/schema.json
- packages/core/src/generators/utils/generate-project.ts
- packages/core/src/models/project-generator-schema.ts
- packages/core/src/models/swagger-executor-configuration.ts
- yarn.lock
> feat(core): support nx-plugin-openapi for more advanced openapi generation

- packages/core/src/executors/update-swagger/executor.ts
> fix(core): resolve startupAssembly to ensure it is always an absolute path

- docs/core/generators/add-swagger-target.md
- packages/core/src/generators/add-swagger-target/schema.json
project -> target
reordered for clarity (in doc) to co-locate with project.
> docs(core): clarify generator option

- packages/core/src/generators/utils/generate-project.ts
> fix(core): install not ran after generating a webapi with useNxPluginOpenAPI

- docs/core/generators/application.md
- packages/core/src/generators/app/schema.json
- packages/core/src/generators/init/generator.spec.ts
- packages/core/src/generators/init/generator.ts
- packages/core/src/generators/utils/generate-project.spec.ts
- packages/core/src/generators/utils/generate-project.ts
> fix(core): adjust gitignore to support generation with directory

- CONTRIBUTING.md
- package.json
- tools/scripts/sandbox.ts
- add steps for using sandbox in CONTRIBUTING.MD
Fix #610
> Addresses #610 - fix(core): remove orphaned publish-local

- docs/core/index.md
- packages/core/generators.json
Had missed one of the descriptions.
@AgentEnder - curious when you might have another release in the hopper?
> docs(core): refine generator descriptions

- packages/utils/src/lib/utility-functions/workspace.ts
> fix(core): check glob for array length

- packages/core/src/generators/import-projects/generator.ts
> fix(core): import-projects should add project.json file for new projects

- packages/core/src/generators/import-projects/generator.ts
> fix(core): add slash to use exact path (#685)

- packages/core/src/generators/swagger-typescript/__snapshots__/generator.spec.ts.snap
- packages/core/src/generators/swagger-typescript/build-typescript-representation/parse-schema-object.ts
- packages/core/src/generators/swagger-typescript/generator.spec.ts
- packages/core/src/generators/swagger-typescript/generator.ts
> fix(core): codegen should not import self and default to required reference types

- packages/core/src/generators/utils/add-to-sln.ts
> fix(core): obey path in solution-file parameter when generating projects

- docs/core/generators/application.md
- docs/core/generators/library.md
- nx.json
- packages/core/src/generators/lib/schema.json
- packages/nxdoc/src/generators/generate-docs/templates/detail/__generatorFileName__.md
> fix(core): should be able to pass extra args to generated libraries

- packages/core/src/generators/add-swagger-target/add-swagger-target.ts
- project.json
> fix(core): read js lib defaults when generating js lib

- docs/core/Executors/build.md
- packages/core/src/executors/build/schema.json
> fix(core): version suffix is a string

- .github/workflows/main.yml
- .github/workflows/pr.yml
- CHANGELOG.md
- nx.json
- packages/core/src/graph/create-dependencies.spec.ts
- packages/core/src/graph/create-dependencies.ts
- packages/core/src/tasks/check-module-boundaries.spec.ts
- packages/core/src/tasks/check-module-boundaries.ts
- packages/dotnet/src/lib/core/dotnet.client.ts
- packages/utils/fixtures/cs/file.csproj
- packages/utils/fixtures/fs/file.fsproj
- packages/utils/fixtures/vb/file.vbproj
- packages/utils/src/lib/utility-functions/workspace.ts
- project.json
Fixes #820
Fixes #335
Fixes #214
> fix(core): read dependencies via dotnet list reference

- packages/core/src/generators/test/generator.ts
- packages/core/src/generators/utils/generate-project.spec.ts
- packages/core/src/generators/utils/generate-project.ts
> fix(core): remove duplicate segments when appending workspace layout dirs

- .gitignore
- e2e/core-e2e/tests/nx-dotnet.spec.ts
- packages/core/src/graph/create-dependencies.ts
- packages/core/tsconfig.lib.json
> chore: include JSON files in TSConfig

- packages/core/src/executors/openapi-codegen/executor.ts
Hi all,
The current command for openapi-generator-cli does not work and needs to be modified to make it work. I propose the following changes to render it fully functional once again.
> fix: updated openapi-codegen command

- .eslintrc.json
- packages/dotnet/src/lib/core/dotnet.client.ts
- tools/eslint-rules/rules/no-terminal-popups.spec.ts
- tools/eslint-rules/rules/no-terminal-popups.ts
It seems like our friend @Den-dp missed the new method I added after #887 was created.
This PR correct this and also update the associated ESLint rule.
> chore(misc): add missing windowsHide

- README.md
The link to the nx-dotnet docs was incorrect and it was upsetting me!
> docs(repo): Update README link
