nx-dotnet/nx-dotnet

- packages/core/src/generators/utils/generate-project.spec.ts
- packages/core/src/generators/utils/generate-project.ts
- packages/core/src/models/build-executor-configuration.ts
Update all output paths to include the full path to the project root, similar to how the official Nx generators will format the output paths. Fixes #27
> Fix output path in project files and build target

- packages/core/src/generators/utils/generate-project.spec.ts
- packages/core/src/generators/utils/generate-project.ts
Do not include serve target for libraries as they cannot be run directly.
Fixes #28
> fix(core): include serve target only for applications

- packages/core/src/generators/restore/generator.ts
Add an unused parameter to keep Nx from overwriting the dotnet client.
> fix(core): add unused options parameter for restore

- package.json
- packages/utils/src/lib/utility-functions/workspace.ts
inconsistent directory separators between .net CLI caused path.resolve to behave weirdly.
fixes #43
> fix(utils): getDependantProjectsForNxProject should work on Unix

- packages/core/executors.json
- packages/core/migrations.json
- packages/core/package.json
- packages/core/src/executors/format/executor.spec.ts
- packages/core/src/executors/format/executor.ts
- packages/core/src/executors/format/schema.d.ts
- packages/core/src/executors/format/schema.json
- packages/core/src/generators/utils/generate-project.spec.ts
- packages/core/src/generators/utils/generate-project.ts
- packages/core/src/migrations/add-lint-target/add-lint-target.ts
- packages/core/src/models/index.ts
- packages/core/src/models/lint-executor-configuration.ts
- packages/dotnet/src/lib/core/dotnet.client.ts
- packages/dotnet/src/lib/models/dotnet-format/dotnet-format-flags.ts
- packages/dotnet/src/lib/models/dotnet-format/dotnet-format-options.ts
- packages/dotnet/src/lib/models/dotnet-format/index.ts
- packages/dotnet/src/lib/models/index.ts
- workspace.json
Add a new executor that runs the dotnet-format tool against the project, which defaults to checking only but can also automatically fix various issues. This executor is then added to all new and existing projects.
Fixes #13
> Add lint support through the dotnet-format tool

- packages/core/src/generators/utils/generate-project.spec.ts
- packages/core/src/generators/utils/generate-project.ts
Remove the capturing parentheses from the split Regex to remove an extra dot from the name of the generated csproj file.
Fixes #60
> Remove extra separator from project names

- packages/core/generators.json
- packages/core/src/generators/test/generator.spec.ts
- packages/core/src/generators/test/generator.ts
- packages/core/src/generators/test/schema.d.ts
- packages/core/src/generators/test/schema.json
- packages/core/src/generators/utils/generate-project.spec.ts
- packages/core/src/generators/utils/generate-project.ts
- packages/core/src/generators/utils/generate-test-project.spec.ts
- packages/core/src/generators/utils/generate-test-project.ts
- packages/core/src/models/index.ts
- packages/core/src/models/test-generator-schema.ts
Add a generator that creates test projects for existing apps/libs
Fixes #68
> feat(core): add test project generator

- e2e/core-e2e/jest.config.js
- e2e/core-e2e/tests/nx-dotnet.spec.ts
- packages/core/src/graph/process-project-graph.ts
Running "nx dep-graph" will currently generate the following error:
nx-dotnet encountered an error parsing dependencies for 'project name'
> FIX: reference existing project file path

- packages/core/src/generators/utils/generate-project.ts
- packages/core/src/migrations/1.2.0/add-module-boundaries-check/migrate.ts
When creating new projects that reside in a directory, the project name that appears in the MSBuild target uses the short name specified in the `--name=` argument rather than the fully qualified nx project name. This causes the project to fail when building with the following error (as the short name cannot be found in the nx config):
```
Checking module boundaries for example-project
(node:19408) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'root' of undefined
at /Users/tom.davis/Contingent/services-dotnet/node_modules/@nx-dotnet/core/src/tasks/check-module-boundaries.js:13:57
at Generator.next (<anonymous>)
at /Users/tom.davis/Contingent/services-dotnet/node_modules/tslib/tslib.js:117:75
at new Promise (<anonymous>)
at Object.__awaiter …
```
> fix(core): use fully qualified project name in msbuild task

- packages/core/src/tasks/check-module-boundaries.ts
When module boundaries are violated, the text shown in the console is similar to the following:
```
alerts-api cannot depend on comments-domain. Project tag [object Object] is not satisfied.
```
This PR stringifies the module boundary JSON to give a little more insight:
```
alerts-api cannot depend on comments-domain. Project tag {"sourceTag":"scope:alerting","onlyDependOnLibsWithTags":["scope:alerting","scope:common"]} is not satisfied.```
> fix(core): display moduleBoundary JSON instead of [object Object]

- packages/core/src/generators/utils/generate-test-project.ts
When creating test projects, the argument passed to the check-module-boundaries.js script in the MSBuild task is the name of the project *under* test; I believe this argument should actually be the name of test project itself.
To recreate:
```
nx generate @nx-dotnet/core:app --name=example-app --language=C# --template=console --standalone --testTemplate=none
<Target Name="CheckNxModuleBoundaries" BeforeTargets="Build">
<Exec Command="node ../../node_modules/@nx-dotnet/core/src/tasks/check-module-boundaries.js -p example-app"/>
</Target>
nx generate @nx-dotnet/core:test --name=example-app --language=C# --testTemplate=xunit --standalone --no-interactive
<Target Name="CheckNxModuleBoundaries" BeforeTargets="Build">
<Exec Command="node …
```
> fix(core): use test project name in msbuild task instead of project under test

- .husky/commit-msg
- .husky/common.sh
- .husky/pre-commit
- .husky/pre-push
> chore(repo): fix Husky hooks failing on Win10

- e2e/core-e2e/jest.config.js
- e2e/core-e2e/tests/nx-dotnet.spec.ts
- packages/core/src/graph/process-project-graph.ts
- tools/scripts/e2e.ts
> fix(core): process project graph shouldn't throw if not a .NET project

- docs/core/guides/handling-solutions.md
- e2e/core-e2e/tests/nx-dotnet.spec.ts
- packages/dotnet/src/lib/core/dotnet.client.ts
- packages/utils/src/lib/utility-functions/parameters.ts
Please review the code before merging it.
> fix(dotnet): should work with paths that contain spaces

- .github/workflows/main.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/smoke.yml
- .releaserc.js
- e2e/core-e2e/tests/nx-dotnet.spec.ts
- nx.json
- packages/core/project.json
- packages/core/src/executors/test/executor.ts
- packages/core/src/generators/app/schema.json
- packages/core/src/generators/lib/schema.json
- packages/core/src/generators/test/schema.json
- packages/dotnet/project.json
- packages/dotnet/src/lib/core/dotnet.client.spec.ts
- packages/dotnet/src/lib/core/dotnet.client.ts
- packages/nx-ghpages/project.json
- packages/nxdoc/project.json
- packages/typescript/project.json
- packages/utils/project.json
- tools/scripts/patch-package-versions/index.ts
- tools/scripts/publish-all/index.ts
- tools/utils/fs.ts
Moving from `execSync` -> `spawnSync` for logAndExecute resulted in some executors returning invalid results. Notably, `nx test` would return `{success: true}` despite the `dotnet test` command failing.
> fix(core): test executor should fail properly

- packages/core/src/generators/nuget-reference/generator.spec.ts
- packages/core/src/generators/nuget-reference/generator.ts
Fixes an issue I came across while running the nuget reference generator.
Basically, the resolved version is not passed to addPackageReference on line 41.
> fix(core): resolved package version not provided

- packages/dotnet/src/lib/core/dotnet.client.spec.ts
- packages/dotnet/src/lib/core/dotnet.client.ts
Expand environment variables before passing args to the child process.
> fix(dotnet): expand env vars in cli parameters

- docs/core/generators/application.md
- docs/core/generators/library.md
- package.json
- packages/core/src/generators/app/schema.json
- packages/core/src/generators/init/generator.ts
- packages/core/src/generators/lib/schema.json
- packages/core/src/generators/test/generator.ts
- packages/core/src/generators/utils/generate-project.spec.ts
- packages/core/src/generators/utils/generate-project.ts
- packages/core/src/generators/utils/generate-test-project.spec.ts
- packages/core/src/generators/utils/generate-test-project.ts
- packages/core/src/generators/utils/prompt-for-template.ts
- packages/core/src/models/project-generator-schema.ts
- packages/dotnet/src/lib/core/dotnet.client.spec.ts
- packages/dotnet/src/lib/core/dotnet.client.ts
- packages/dotnet/src/lib/core/dotnet.factory.ts
- packages/dotnet/src/lib/models/dotnet-new/dotnet-template.ts
- packages/dotnet/src/lib/utils/parse-dotnet-new-list-output.ts
- tools/scripts/sandbox.ts
- yarn.lock
Previously, we prompted with a link to MSDN and a free-text field. Now, we run `dotnet new --list` to generate the list of possible templates, filtering by the value provided by `--template {v}`. This results in a select instead of freetext, that is filtered by language and search term.
> feat(core): update prompt for installed template to present available options

- packages/core/src/executors/format/executor.ts
- packages/dotnet/src/lib/core/dotnet.client.ts
Nx .NET always runs dotnet-format via the tool, since the included version of the tool is broken.
Nx .NET takes advantage of the builtin since it is no longer broken.
Fixes #435
> fix(core): remove workaround for broken dotnet format builtin

- docs/core/generators/application.md
- docs/core/generators/test.md
- e2e/core-e2e/tests/nx-dotnet.spec.ts
- packages/core/src/generators/app/generator.spec.ts
- packages/core/src/generators/app/schema.json
- packages/core/src/generators/import-projects/generator.spec.ts
- packages/core/src/generators/import-projects/generator.ts
- packages/core/src/generators/init/generator.spec.ts
- packages/core/src/generators/init/generator.ts
- packages/core/src/generators/init/templates/root/Directory.Build.props__tmpl__
- packages/core/src/generators/init/templates/root/Directory.Build.targets__tmpl__
- packages/core/src/generators/lib/generator.spec.ts
- packages/core/src/generators/test/generator.spec.ts
- packages/core/src/generators/test/generator.ts
- packages/core/src/generators/test/schema.json
- packages/core/src/generators/utils/generate-project.spec.ts
- packages/core/src/generators/utils/generate-project.ts
- packages/core/src/generators/utils/generate-test-project.spec.ts
- packages/core/src/generators/utils/generate-test-project.ts
- packages/core/src/models/project-generator-schema.ts
- packages/core/src/models/test-generator-schema.ts
- packages/core/src/tasks/check-module-boundaries.ts
Extending the `@nx-dotnet/core:init` generator to include initialization of MSBuild customization files `Directory.Build.props` and `Directory.Build.targets`. The targets file is a placeholder for workspaces to configure customization that should be imported later. The props file includes build output path properties equivalent to what is currently added per project via XML manipulation.  
Some remaining work:
> feat(core): adding templates with default output path properties to init generator

- .github/workflows/main.yml
- .github/workflows/pr.yml
- packages/utils/src/lib/utility-functions/workspace.ts
This can throw an error whenever you don't specify a source root.
Fixes issue: https://github.com/nx-dotnet/nx-dotnet/issues/465
> fix(core): getProjectFilesForProject should consider project root in addition to source root

- packages/core/src/tasks/check-module-boundaries.ts
The msg that is logged to the console should not log undefined.
> fix(core): check-module-boundaries should not log undefined as project name

- packages/core/src/generators/init/templates/root/Directory.Build.props__tmpl__
- packages/core/src/generators/init/templates/root/Directory.Build.targets__tmpl__
> fix(core): allow open solutions with Visual Studio

- packages/core/src/generators/init/templates/root/Directory.Build.targets__tmpl__
- packages/core/src/tasks/check-module-boundaries.spec.ts
- packages/core/src/tasks/check-module-boundaries.ts
- packages/utils/src/lib/utility-functions/workspace.ts
check-module-boundaries is failing on windows since single quotes are not consumed by the shell before passing into yargs.
> fix(core): check-module-boundaries should work if single quotes not consumed by shell

- demo/apps/webapi/NxDotnet.Test.Webapi.csproj
- demo/apps/webapi/Program.cs
- demo/libs/csharp-models/NxDotnet.Demo.Libs.CsharpModels.csproj
- global.json
- packages/core/src/executors/build/executor.ts
- packages/core/src/generators/utils/get-path-to-startup-assembly.ts
- packages/utils/src/lib/utility-functions/workspace.ts
Hit a weird issue when updating to .NET 7.
- Updating .NET changes the subdir within output path that contains your code (e.g. dist/apps/my-api/bin/net7.0 instead of dist/apps/my-api/bin/net6.0).
- We infer the path to your output when extracting swagger documentation, by globbing for .dll files that match your project's name inside of the root dist folder and using the first match. (e.g. glob(dist/apps/my-api/**/my-api.dll)[0])
- If you don't remember to clean the dist folder, the .NET build's old results end up in the nx cache.
All of the above combined get you a poisoned cache for nx build my-api that causes nx swagger my-api to fail.
- swagger executor will error appropriately when it finds multiple matching DLLs, instead of using the first silently. If you target is meant to create …
> fix(core): prevent stale cache entries from breaking swagger on dotnet upgrades

- e2e/core-e2e/tests/nx-dotnet.spec.ts
- packages/core/src/generators/utils/generate-project.ts
- packages/core/src/generators/utils/generate-test-project.spec.ts
codegenProject is generated using nrwl/js which applies nx file naming conventions. Codegen/swagger projects are json/ts libraries so they don't really have to follow dotnet conventions. This adds new nxProjectName normalized option in project generator. This filename is not affected by pathScheme and is used for swaggerProject and codegenProject
fixes https://github.com/nx-dotnet/nx-dotnet/issues/627
> fix(core): app swaggerLib generation should work using dotnet pathScheme

- packages/dotnet/src/lib/core/dotnet.client.ts
Fix #657
Example usage in custom executor:
```ts
const { name, context, project, outputDir, additionalArguments } = options;
const projectDir = normalizePath(dirname(projectFile));
const paramaters = {
'startup-project': pathResolve(workspaceRoot, projectDir),
'project': pathResolve(workspaceRoot, project),
'context': context,
'msbuildprojectextensionspath': pathResolve(workspaceRoot, `./dist/intermediates/${project}/obj`)
}
if (outputDir) {
paramaters['output-dir'] = pathResolve(workspaceRoot, outputDir)
}
let extraParameters;
if (additionalArguments) {
extraParameters = `-- ${additionalArguments}`;
}
dotnetClient.runTool('dotnet-ef', ['migrations', 'add', name ], paramaters, extraParameters);
```
With a target like this:
```ts
"ef-migrations": {
"executor": "@org/dotnet-ef:migrations", …
```
> feat(core): extra parameters support for run tool

- packages/core/src/migrations/1.8.0/remove-output-option.spec.ts
- packages/utils/src/lib/utility-functions/workspace.ts
Fixes https://github.com/nx-dotnet/nx-dotnet/issues/646
Turns out the loop was being skipped over. In JS `for in` will not iterate a Map. Switched to a `for of` loop.
NOTES:
Have a unit test but did not include it because fast glob is running against the file system so the unit test is rigged.
fast glob is supposed to support an `fs` option to use an alternative file system, however, I could not get this to work with tree. Adding a virtual file system was out of scope since this is a single line fix.
> fix(core): use for of on loop on project Map

- packages/core/src/tasks/check-module-boundaries.spec.ts
- packages/core/src/tasks/check-module-boundaries.ts
To fix the rescope that came in [v16 of nx](https://blog.nrwl.io/nx-16-is-here-69584ec87053#8e44).
Is backwards compatible with the old name, so no breaking changes/migrations needs.
> fix(core): support new name for enforce-module-boundaries eslint rule

- packages/core/src/executors/update-swagger/executor.spec.ts
- packages/core/src/executors/update-swagger/executor.ts
By moving the working directory of the swagger tool run the project directory, the generation can rely on external config files (like appsettings.json)
> feat(core): make swagger tool run in project directory

- packages/core/src/executors/format/executor.spec.ts
- packages/core/src/executors/format/executor.ts
- packages/core/src/executors/update-swagger/executor.spec.ts
- packages/core/src/executors/update-swagger/executor.ts
- packages/utils/src/lib/models/dotnet-tools-manifest.interface.ts
- packages/utils/src/lib/models/index.ts
- packages/utils/src/lib/utility-functions/dotnet-tools-manifest.spec.ts
- packages/utils/src/lib/utility-functions/dotnet-tools-manifest.ts
- packages/utils/src/lib/utility-functions/index.ts
The current code is written with the assumption that the tools manifest files looks like:
```json
{
"version": 1,
"isRoot": true,
"tools": {
"swashbuckle.aspnetcore.cli": "6.5.0"
}
}
```
when it is actually 
```json
{
"version": 1,
"isRoot": true,
"tools": {
"swashbuckle.aspnetcore.cli": {
"version": "6.5.0",
"commands": ["swagger"]
}
}
}
```
Also, the tool name is case insensitive.
So I wrote some util functions and interfaces to read the file in a type safe way.
The bug just caused you to reinstall the tool even though it was already installed.
> fix(core): update-swagger executor always reinstalls tool

- docs/core/generators/application.md
- e2e/core-e2e/tests/nx-dotnet.spec.ts
- packages/core/src/generators/app/schema.json
- packages/core/src/generators/utils/generate-project.spec.ts
- packages/core/src/generators/utils/generate-project.ts
- packages/core/src/generators/utils/generate-test-project.spec.ts
- packages/core/src/models/project-generator-schema.ts
- packages/dotnet/src/lib/core/dotnet.client.ts
I've moved my version of this feature to its own PR.
This version is able to accept args passed after `--` using the additionalProperties feature from JSON-Schema.
Closes: #398 
Closes: #262
> feat(core): add argument forwarding to dotnet new

- e2e/core-e2e/tests/nx-dotnet.spec.ts
- package.json
- packages/core/src/graph/process-project-graph.ts
- packages/dotnet/src/lib/core/dotnet.client.spec.ts
- packages/dotnet/src/lib/core/dotnet.client.ts
- packages/dotnet/src/lib/core/dotnet.factory.ts
- packages/utils/src/lib/utility-functions/parameters.ts
- tools/scripts/e2e.ts
Updates dotnet client's format method to handle passing new args format that was introduced when the tool was brought into the dotnet CLI
This includes running 1-3 commands as needed rather than a single command since they no longer support disabling a single class of failure
Fixes: #623
> fix(dotnet): update args handling for dotnet format

- packages/core/src/generators/move/generator.spec.ts
- packages/core/src/generators/move/generator.ts
project.json paths weren't being updated correctly
- `nx g @nx-dotnet/core:lib my-lib`
- `nx g @nx-dotnet/core:move --projectName my-lib --destination a/b/c`
- `nx g @nx-dotnet/core:move --projectName a-b-c --destination my-lib`
- `sourceRoot`, `outputPaths`, etc should be pathed correctly
Note: when this issue was discovered we noted `$schema` was also incorrect following the generator.  This hasn't been reproducible but does show itself in the added unit test.
> fix(core): move generator not updating paths correctly

- packages/core/src/tasks/check-module-boundaries.spec.ts
- packages/core/src/tasks/check-module-boundaries.ts
- packages/utils/src/lib/models/nx.ts
Addresses #768 
Also adds regex and glob matching - another feature of [@nx/eslint-plugin](https://nx.dev/core-features/enforce-module-boundaries#tag-formats)
> feat(core): support allSourceTags (#768) and wildcards in check-module-boundaries.js

- packages/utils/src/lib/utility-functions/workspace.ts
The source file path should be normalized s.t. Nx can find it in the file map.
> fix(core): createDependencies should work on windows

- packages/dotnet/src/lib/core/dotnet.client.spec.ts
- packages/dotnet/src/lib/core/dotnet.client.ts
When using the new .net 6 format flags, it would pass `--verifyNoChanges` instead of `---verify-no-changes`, which would not work.
This fixes that by passing the args for the new commands through the normal swap keys function.
> fix(dotnet): correct flag passed to client to verify no changes

- packages/core/src/generators/import-projects/generator.ts
- packages/core/src/generators/init/generator.spec.ts
- packages/core/src/generators/init/generator.ts
- packages/core/src/generators/nuget-reference/generator.ts
- packages/core/src/generators/sync/generator.ts
- packages/core/src/graph/create-nodes.ts
- packages/utils/src/lib/utility-functions/config.ts
There's an issue with how we read configuration in Nx 17. It results in default values not being applied for some options, and project inference not working after migration.
This updates config handling to merge all values rather than relying on nullish handling.
> fix(core): options should be read correctly for project inference

- packages/core/src/executors/build/schema.json
- packages/core/src/executors/publish/schema.json
Prior to this change the schema.jsons for build and publish required the build configuration to be either Debug or Release. This change removes that restriction, allowing build configurations with other names.
I confirmed via monkey-patch that this fixes the issue in my local repository
> fix(core): remove restriction of configuration

- packages/dotnet/src/lib/core/dotnet.client.spec.ts
- packages/dotnet/src/lib/core/dotnet.client.ts
- packages/dotnet/src/lib/models/dotnet-add-package/dotnet-add-package-flags.ts
- packages/dotnet/src/lib/models/dotnet-build/dotnet-build-flags.ts
- packages/dotnet/src/lib/models/dotnet-format/dotnet-format-flags.ts
- packages/dotnet/src/lib/models/dotnet-new/dotnet-new-flags.ts
- packages/dotnet/src/lib/models/dotnet-publish/dotnet-publish-flags.ts
- packages/dotnet/src/lib/models/dotnet-run/dotnet-run-flags.ts
- packages/dotnet/src/lib/models/dotnet-test/dotnet-test-flags.ts
- packages/utils/src/lib/utility-functions/args.spec.ts
- packages/utils/src/lib/utility-functions/args.ts
- packages/utils/src/lib/utility-functions/parameters.spec.ts
- packages/utils/src/lib/utility-functions/parameters.ts
fixes #812
Made the keys that need the word "false" an explicit thing to handle, since it seems to be the exception.
I am not sure if there are other flags that need to be this explicit false thing. I could only handle the ones that have test cases written.
I have also refactored the handling of converting options to params, since it is repeating the same calls over and over.
> fix(dotnet): prevent "false" being incorrectly passed to dotnet command

- apps/docs-site/src/pages/index.js
Fixes the incorrect spelling of _release_ on the landing page
> docs: fix typo on landing page

- packages/core/src/graph/create-nodes.ts
Fixes the Nx warning `Project 'xxx.xxx' contains extension with invalid name (type).`
> Fix warning "Project 'xxx' contains extension with invalid name (type)."

- packages/core/src/executors/serve/executor.ts
- packages/dotnet/src/lib/core/dotnet.client.spec.ts
- packages/dotnet/src/lib/models/dotnet-run/dotnet-run-flags.ts
- packages/utils/src/lib/utility-functions/parameters.spec.ts
- packages/utils/src/lib/utility-functions/parameters.ts
In .NET 8 some changes made passing `--configuration Debug` invalid. This PR swaps that to look more like `--property:Configuration=Debug` wihch should work in both .NET 8 and lower
Fixes #865
> fix(dotnet): serve should work with dotnet 8

- apps/docs-site/project.json
- docs/nx-ghpages/Executors/deploy.md
- package.json
- packages/core/src/executors/serve/executor.ts
- packages/core/src/generators/swagger-typescript/generator.spec.ts
- packages/nx-ghpages/src/executors/deploy/executor.spec.ts
- packages/nx-ghpages/src/executors/deploy/executor.ts
- packages/nx-ghpages/src/executors/deploy/schema.d.ts
- packages/nx-ghpages/src/executors/deploy/schema.json
Remote + Directory must be specified in nx-ghpages:deploy options every time.
Remote + Directory are inferred based on context if possible
> feat(nx-ghpages): intuit directory and remote when possible

- package.json
- packages/core/package.json
- packages/dotnet/package.json
Nx release doesn't replace version specified by `*`, whereas our custom script used to do so
Fixes https://github.com/nx-dotnet/nx-dotnet/issues/876
> fix(repo): published packages should include resolved versions

- packages/core/package.json
Fixes https://github.com/nx-dotnet/nx-dotnet/issues/888
> chore: relax version peerdep for openapi cli

- .all-contributorsrc
- demo/apps/web-frontend/src/index.html
- packages/core/project.json
- packages/core/src/generators/swagger-typescript/generator.ts
- packages/core/src/graph/create-dependencies.ts
- packages/dotnet/src/lib/core/dotnet.client.ts
- packages/utils/src/lib/utility-functions/config.ts
- packages/utils/src/lib/utility-functions/e2e/nx.ts
- tools/scripts/stop-local-registry.ts
> perf: parallelize create dependencies processing
